#!/usr/bin/env bash
set -euo pipefail

NEW_CODE=
INSTALL_ROOT=
CONF_LOGICAL=/etc/ares/usage-upload.conf
WRAPPER_LOGICAL=/usr/local/sbin/ares_prepare_usage_upload.sh
BACKUP_ROOT_LOGICAL=/var/backups/ares-usage-collection
MAX_UPLOAD_BYTES=2097152

usage() {
  cat <<'USAGE'
Usage:
  sudo ares-set-school-code ARES-S00XX

Changes only the installed ARES usage-export school code. The command:

  * accepts a final canonical ID in ARES-S0000 format;
  * backs up /etc/ares/usage-upload.conf;
  * atomically writes the new ID;
  * runs an AUTO export smoke test; and
  * automatically restores the prior configuration if verification fails.

Options:
  --install-root PATH  Testing only: prefix installed paths with PATH
  -h, --help           Show this help
USAGE
}

die() { echo "ERROR: $*" >&2; exit 1; }
info() { echo "==> $*"; }

while (($#)); do
  case "$1" in
    --install-root) INSTALL_ROOT=${2:-}; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    -*) die "Unknown option: $1" ;;
    *)
      [[ -z "$NEW_CODE" ]] || die "Only one school code may be supplied"
      NEW_CODE=$1
      shift
      ;;
  esac
done

[[ -n "$NEW_CODE" ]] || { usage >&2; die "Final school code is required"; }
[[ "$NEW_CODE" =~ ^ARES-S[0-9]{4}$ ]] || die "Final school code must match ARES-S0000"

if [[ -z "$INSTALL_ROOT" && ${EUID:-$(id -u)} -ne 0 ]]; then
  die "Run as root (normally with sudo), or use --install-root for a sandbox test"
fi
if [[ -n "$INSTALL_ROOT" ]]; then
  [[ "$INSTALL_ROOT" = /* ]] || die "--install-root must be an absolute path"
  [[ -d "$INSTALL_ROOT" ]] || die "--install-root does not exist: $INSTALL_ROOT"
  INSTALL_ROOT=$(cd -- "$INSTALL_ROOT" && pwd)
fi

rooted() {
  local logical=$1
  if [[ -n "$INSTALL_ROOT" ]]; then
    printf '%s%s' "$INSTALL_ROOT" "$logical"
  else
    printf '%s' "$logical"
  fi
}

for cmd in cp date python3; do
  command -v "$cmd" >/dev/null 2>&1 || die "Required command not found: $cmd"
done

CONF_ACTUAL=$(rooted "$CONF_LOGICAL")
WRAPPER_ACTUAL=$(rooted "$WRAPPER_LOGICAL")
BACKUP_ROOT_ACTUAL=$(rooted "$BACKUP_ROOT_LOGICAL")

[[ -f "$CONF_ACTUAL" && -r "$CONF_ACTUAL" ]] || die "Installed configuration is unavailable: $CONF_LOGICAL"
[[ -x "$WRAPPER_ACTUAL" ]] || die "Installed export wrapper is unavailable: $WRAPPER_LOGICAL"

# The installed configuration is root-owned and generated by the ARES installer.
# shellcheck source=/dev/null
source "$CONF_ACTUAL"
OLD_CODE=${SCHOOL_CODE:-}
[[ -n "$OLD_CODE" ]] || die "Installed configuration has no SCHOOL_CODE"

if [[ "$OLD_CODE" == "$NEW_CODE" ]]; then
  info "School code is already $NEW_CODE; no change was made"
  exit 0
fi

STAMP=$(date +%Y%m%d_%H%M%S)
BACKUP_DIR="$BACKUP_ROOT_ACTUAL/${STAMP}_school-code_$$"
BACKUP_FILE="$BACKUP_DIR$CONF_LOGICAL"
mkdir -p "$(dirname -- "$BACKUP_FILE")"
cp -a -- "$CONF_ACTUAL" "$BACKUP_FILE"
info "Backed up $CONF_LOGICAL"

CHANGED=0
restore_prior_config() {
  trap - ERR HUP INT TERM
  if ((CHANGED)); then
    set +e
    cp -a -- "$BACKUP_FILE" "$CONF_ACTUAL"
    echo "ERROR: Verification failed; restored the prior school code $OLD_CODE" >&2
  fi
}
rollback_error() {
  local rc=$?
  restore_prior_config
  exit "$rc"
}
rollback_signal() {
  local rc=$1
  restore_prior_config
  exit "$rc"
}
trap rollback_error ERR
trap 'rollback_signal 129' HUP
trap 'rollback_signal 130' INT
trap 'rollback_signal 143' TERM

python3 - "$CONF_ACTUAL" "$NEW_CODE" <<'PY'
import os
from pathlib import Path
import stat
import sys

path = Path(sys.argv[1])
school_code = sys.argv[2]
original = path.read_text(encoding='utf-8').splitlines(keepends=True)
matches = [index for index, line in enumerate(original) if line.startswith('SCHOOL_CODE=')]
if len(matches) != 1:
    raise SystemExit(f'expected exactly one SCHOOL_CODE assignment, found {len(matches)}')

line_ending = '\n' if original[matches[0]].endswith('\n') else ''
original[matches[0]] = f'SCHOOL_CODE={school_code}{line_ending}'
metadata = path.stat()
temporary = path.with_name(f'.{path.name}.tmp.{os.getpid()}')
try:
    with temporary.open('x', encoding='utf-8') as stream:
        stream.writelines(original)
        stream.flush()
        os.fsync(stream.fileno())
    os.chmod(temporary, stat.S_IMODE(metadata.st_mode))
    os.chown(temporary, metadata.st_uid, metadata.st_gid)
    os.replace(temporary, path)
finally:
    if temporary.exists():
        temporary.unlink()
PY
CHANGED=1

info "Running AUTO export smoke test for $NEW_CODE"
SMOKE_OUTPUT=$(ARES_UPLOAD_CONF="$CONF_ACTUAL" "$WRAPPER_ACTUAL" AUTO)
LAST_LINE=$(printf '%s\n' "$SMOKE_OUTPUT" | tail -n 1)
SMOKE_RESULT=$(python3 - "$LAST_LINE" "$NEW_CODE" "$MAX_UPLOAD_BYTES" <<'PY'
import json
import os
import sys

obj = json.loads(sys.argv[1])
school_code = sys.argv[2]
max_bytes = int(sys.argv[3])
expected_prefix = f'ARES_USAGE_{school_code}_AUTO_'
path = obj.get('path')
filename = obj.get('filename')
assert obj.get('collection') == 'AUTO', obj
assert isinstance(filename, str) and filename.startswith(expected_prefix), obj
assert path and os.path.isfile(path), path
size = os.path.getsize(path)
assert 0 < size <= max_bytes, f'export size {size} is outside 1..{max_bytes}'
assert obj.get('bytes') == size, obj
print(f'{filename}|{size}')
PY
)

CHANGED=0
trap - ERR HUP INT TERM
SMOKE_FILENAME=${SMOKE_RESULT%%|*}
SMOKE_BYTES=${SMOKE_RESULT##*|}

cat <<EOF

ARES school-code reassignment complete.
Previous school code: $OLD_CODE
New school code: $NEW_CODE
Configuration backup: ${BACKUP_FILE#"$INSTALL_ROOT"}
Verified AUTO export: $SMOKE_FILENAME
Measured usage CSV: $SMOKE_BYTES bytes
EOF
